Game logic
guillainbisimwa/tic-tac-toe-game pull request #3
Opened 2020-10-14 20:38 UTC by guillainbisimwa

- Get user input
- DIsplay the board
- Implement the wining logic
- Check and valid every user move

2020-10-14 22:40 UTC, blackpintz requested changes
# Status: Changes Required.

## Hello team.

**Your application is impressive. However, there are a few changes needed before the project can be approved.**

1). **Please remove the inline comments in all the files.**
2). **Move all game-logic related resources (classes and/or modules) to the lib directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from pathwright).**

3). **The project should respect the single responsibility rule. That means all the classes/ methods should do one thing. Example, the `TicTacToe class` is creating board, setting players and checking if the game is a win/draw. Choose among one of the three responsibilities for the `TicTacToe class` and create classes for the rest. You can use methods/ modules but please note that you are required to use a minimum of two classes. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from pathwright).**

**Check one comment below.**

### Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

2020-10-14 22:40 UTC, blackpintz commented on bin/main
>  end
## Mandatory
Define a method you can reuse to check the winning position of each player, instead of using duplicate code.

2020-10-15 22:16 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

## Hi team, good job on making the previously required changes!
Your project meets most of the requirements  👏 
You just have to implement one minor (and very simple) change in order to move on
 
## [REQUIRED CHANGES]

- [x] No puts/print and get.chomp outside main.rb file ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png)).
- [x] Also the name of your logic file isn't really descriptive. "messages" isn't a good choice for a file that does a lot of stuff than messages. I strongly suggest you guys to give it a proper name like game_logic.rb, for example.

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-10-15 22:16 UTC, kevincappuccino commented on lib/messages.rb
> +    puts player_msg.to_s
- [ ] No puts/print and get.chomp outside main.rb file.

2020-10-15 22:53 UTC, kevincappuccino approved these changes
# [STATUS] PROJECT APPROVED 🍾

### Hey @guillainbisimwa and @Kingobaino1 this is one of the bests Tic-Tac-Toe projects I've ever reviewed! I loved those colors on the terminal, The game is well structured, with clear instructions, and is working perfectly fine. Congrats team, you guys did an excellent job, you have my approval to go ahead and merge this pull request!

_**Clean and modular code, following the best practices and the design looks great, keep it up!**_ 🥇



## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-10-15 22:55 UTC, kevincappuccino commented
## I also left my ⭐
![image](https://user-images.githubusercontent.com/56762529/96194224-51c27280-0f20-11eb-8b69-1dfb18e4614a.png)
### Keep rocking guys! 🚀🔥

2020-10-15 23:02 UTC, merged